version: 2
jobs:
  debug_build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: make debug
      - run: env BUILD=debug make test
  release_build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: make
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - debug_build
      - release_build
